CREATE TABLE "TRAINS" 
(	"ID" NUMBER, 
	"NAME" VARCHAR2(255),

	CREATE UNIQUE INDEX "TRAINS_PK" ON "TRAINS" ("ID"),
	ALTER TABLE "TRAINS" ADD CONSTRAINT "TRAINS_PK" PRIMARY KEY ("ID") ENABLE,
	ALTER TABLE "TRAINS" MODIFY ("ID" NOT NULL ENABLE)
)

CREATE TABLE "WAGONS" 
(	"ID" NUMBER, "NAME" VARCHAR2(255), 
	"SEATS" NUMBER, 
	"TRAIN_ID" NUMBER DEFAULT 0,

	CREATE UNIQUE INDEX "WAGONS_PK" ON "WAGONS" ("ID"),
	ALTER TABLE "WAGONS" ADD CONSTRAINT "WAGONS_PK" PRIMARY KEY ("ID") ENABLE,
	ALTER TABLE "WAGONS" MODIFY ("ID" NOT NULL ENABLE),
	CONSTRAINT WAGON_FK FOREIGN KEY (TRAIN_ID) REFERENCES TRAINS(ID);
)

